version: "3.3"

services:
  grafana:
    container_name: grafana 
    image: "grafana/grafana:9.1.6"
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource

  loki:
    container_name: loki
    image: "grafana/loki:2.9.1"
    ports:
      - "3100:3100"
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml

  wspmsg:
    container_name: wspmsg
    restart: always
    build:
      context: ./msg
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - wspmsg.env
