version: "3.3"

services:
  grafana:
    container_name: grafana 
    image: "grafana/grafana:9.1.6"
    ports:
      - "80:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource

  loki:
    container_name: loki
    image: "grafana/loki:2.9.1"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml

  wspmsg:
    container_name: wspmsg
    build:
      context: ./msg
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TREBLE_URL=https://main.treble.ai/deployment/api/poll/
      - TREBLE_API_KEY=ak_8KDqVduAjW5gnSKe_IG5UqF9a1ko97jOPg
      - TREBLE_POLL_ID=489978
      - PHONES=+51-952713764,+51-914553528
