version: "3.3"

services:
  grafana:
    container_name: grafana 
    image: "grafana/grafana:8.4.2"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-storage:/var/lib/grafana
    environment:
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource

  loki:
    container_name: loki
    image: "grafana/loki:2.4.2"
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/mnt/config/loki.yml
      - ./rules.yml:/etc/loki/rules/fake/rules.yml

  # promtail:
  #   image: "grafana/promtail:2.4.2"
  #   volumes:
  #     - logs_dir:/tmp/log
  #     - ./promtail.yml:/etc/promtail/config.yaml
  #   command: -config.file=/etc/promtail/config.yaml

  # flog:
  #   image: "mingrammer/flog:0.4.3"
  #   command: -f json -t log -o /tmp/log/json.log -d 200ms -w -l
  #   volumes:
  #     - logs_dir:/tmp/log

  # nodejs-app:
  #   build: nodejs_app
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - PORT=5001

  # python-app:
  #   build: python_app
  #   ports:
  #     - "5002:5002"
  #   environment:
  #     - PORT=5002

  # php-app:
  #   build: php_app
  #   ports:
  #     - "5003:80"
  #   environment:
  #     - PORT=5003
      
volumes:
  logs_dir:
