version: "3.3"

services:
  grafana:
    container_name: grafana 
    image: "grafana/grafana:9.1.6"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-storage:/var/lib/grafana
    environment:
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource

  loki:
    container_name: loki
    image: "grafana/loki:2.9.1"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
      
volumes:
  logs_dir:
