{
 "title": "Grafana Loki Dashboard for NGINX Service Mesh",
 "description": "Loki v2+ showcase using JSON NGINX access logs.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flogs\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"flogs\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({job=\"flogs\"}[$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (sum_over_time({job=\"flogs\"} | json | unwrap bytes |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "📊 Dashboard created by Ward Bekker (hope you like it!)\n\n🐦 Follow me on [Twitter](https://twitter.com/wardbekker) & [LinkedIn](https://www.linkedin.com/in/wardbekker/) for  Grafana Loki updates \n\n🎥 Check out my [Grafana Loki video's](https://www.youtube.com/playlist?list=PLDGkOdUX1UjqEzcxQrbROMy8DN7MZv_h4) on Youtube"
   }
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (host) (count_over_time({job=\"flogs\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "# NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"flogs\"}[$__interval])"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flogs\"} | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({job=\"flogs\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"flogs\"} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({job=\"flogs\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "geo",
        "type": "string",
        "values": [ "ES" ]
       }
      ],
      "meta": {
       "preferredVisualisationType": "nodeGraph"
      }
     }
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_code) (count_over_time({job=\"flogs\"} | label_format geoip_country_code=\"ES\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"flogs\"} | json | line_format \"➡️ {{.method}} {{.request}} with HTTP status: {{.status}} \""
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "95th percentile of Request Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(quantile_over_time(0.95,{job=\"flogs\"} | json | unwrap bytes |  __error__=\"\"  [$__interval]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "sum(max_over_time({job=\"flogs\"} | json | unwrap bytes |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"flogs\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sum_over_time({job=\"flogs\"} | json | status=200 | unwrap bytes |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, sum by (referer) (count_over_time({job=\"flogs\"} | json |  referer != \"\" and referer !~ \".*?$host.*?\" and referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, sum by (user_identifier) (count_over_time({job=\"flogs\"}  | json | status = 200 and request != \"/\" and user_identifier != \"-\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{user_identifier}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, sum by (host, geoip_country_code) (count_over_time({job=\"flogs\"} | json | label_format geoip_country_code=\"ES\"|  __error__=\"\" [$__interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, sum by (request) (count_over_time({job=\"flogs\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | status = 200 and request != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}